### ISSUE TITLE
Website for documentation

### ISSUE THREAD

**Issue by TomPham97** [JoaoLages/diffusers-interpret#15]
What would you like your documentation website to look like? I would like to help creating and/or maintaining it.
I have some [experience](https://tompham97.github.io/) with Github Pages built via Jekyll. If you want something similar, would you mind creating a `gh-pages` branch and choose a Jekyll theme of choice?

**Comment by JoaoLages** [comment]
I think the easiest way is to have the website read directly from the `main` branch and build the documentation from the docstrings. 
Seems like a lot of people are using [mkdocs](https://realpython.com/python-project-documentation-with-mkdocs/) nowadays.

**Comment by TomPham97** [comment]
Moved to PR #18.
