### ISSUE TITLE
cannot import name '_png' from 'matplotlib'

### ISSUE THREAD

**Issue by rajshah4** [JoaoLages/diffusers-interpret#17]
I received this error, `cannot import name '_png' from 'matplotlib'` when trying to run the new plot command when using Google Colab.

It seems Colab has an older version of matplotlib running - 3.2.2
If I forced an install of matplotlib, `pip install -U matplotlib` and restarted the runtime, I could get the plot to work correctly.

Plot is helpful!

**Comment by JoaoLages** [comment]
Did you run the second cell?
```
!pip install -U diffusers-interpret
!pip install matplotlib==3.1.3
```
Because matplotlib has a strange bug in Colab and requires that version to work. I just ran the notebooks from top to bottom and they worked.

**Comment by rajshah4** [comment]
My bad, I was running the existing notebook I had. I didn't see you updated the example notebook.
