### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by jonfernandes** [JoaoLages/diffusers-interpret#4]
When I try the following code snippet from your notebook I get a TypeError

```
prompt = "A cute corgi with the Eiffel Tower in the background"

generator = torch.Generator(device).manual_seed(2022)
with torch.autocast('cuda') if device == 'cuda' else nullcontext():
    output = explainer(
        prompt, 
        num_inference_steps=15, 
        generator=generator
    )
```

TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by JoaoLages** [comment]
Sorry about that! 
Run `pip install -U diffusers-interpret` to update to the [version 0.2.4](https://github.com/JoaoLages/diffusers-interpret/releases/tag/v0.2.4) that should have those issues fixed.
You can also directly run on [Google Colab](https://colab.research.google.com/drive/16m1HA3guhvP-uJRGMhD0gvuaMAUiiqUc?authuser=1#scrollTo=jKd5c5oUBmNP) 😄
