### ISSUE TITLE
The Colab Notebook cannot be opened

### ISSUE THREAD

**Issue by edgartaor** [JoaoLages/diffusers-interpret#6]
```
Notebook loading error
There was an error loading this notebook. Ensure that the file is accessible and try again.

Invalid Credentials
```

Problably the notebook it is not set to public.

**Comment by JoaoLages** [comment]
Aren't you able to open the link below? I was, even on incognito window.
https://colab.research.google.com/drive/16m1HA3guhvP-uJRGMhD0gvuaMAUiiqUc?authuser=1#scrollTo=jKd5c5oUBmNP

**Comment by JoaoLages** [comment]
Sorry about that, and thanks for posting an issue on this. 
Try this link now: https://colab.research.google.com/github/JoaoLages/diffusers-interpret/blob/main/notebooks/stable_diffusion_example_colab.ipynb

**Comment by edgartaor** [comment]
Thanks! That worked
